### ISSUE TITLE
The ability to add all slash commands from a file in one command

### ISSUE THREAD

**Issue by parafoxia** [tandemdude/hikari-lightbulb#126]
### Summary
Currently, when loading an extension, you need to add all slash commands in that extension manually, or create something like the following to do it automatically:

```py
import inspect
import sys

from lightbulb import slash_commands

...

def load(bot) -> None:
    for _, obj in inspect.getmembers(sys.modules[__name__], inspect.isclass):
        if issubclass(obj, slash_commands.SlashCommand):
            bot.add_slash_command(obj)
```

It would be nice to abstract this away from the user in some nice and convenient way, but as I elude to later, I am not positive there is an "ideal" implementation for something like this.

### Problem
There isn't really a problem, per se, but would allow for extra convenience on the user's side, as many would like to have the autoscan method.

### Ideal implementation
I'm not sure. Either some `load_slash_commands` equivalent of `load_extensions` (which would remove the ability for custom behaviours, potentially), or a method in the `slash_commands` (maybe something like `auto_load`) that can scan the current file for slash commands and add them (though this may be unintuitive).

### Checklist
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by parafoxia** [comment]
Another idea: this could potentially done through an `auto_load_slash` kwarg in load_extension/s or something.

**Comment by tandemdude** [comment]
This is implemented and will be included in the next release.
