### ISSUE TITLE
Adding a new navigator for use in slash commands with buttons

### ISSUE THREAD

**Issue by neonjonn** [tandemdude/hikari-lightbulb#129]
### Summary
Adding a new navigator for use in slash commands utilising buttons.
This is a new class called SlashNavigation, and works with pages from both StringPaginator and EmbedPaginator

### Problem
Solves the fact that StringNavigation and EmbedNavigation can't be used within slash commands

### Ideal implementation
Implemented on my fork here: https://github.com/neonjonn/hikari-lightbulb

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by olliequ** [comment]
@neonjonn Hey, commenting here is legit the only way I've found I can contact you. I just wanted to say I'm building a Discord bot for the very first time and used your guide https://neonjonn.readthedocs.io/en/latest/hikari-get-started/lightbulb.html. 

I noticed at the bottom you mentioned the next update to the guide will be '_cooldowns for commands_' and '_error handling_'. I am super keen to learn about doing these with hikari & lightbulb, so if you felt like updating the guide with those things all I can say is _please_ do as what you have wrote thus far is super useful and intuitive, and is helping loads of people (just like me!) :)
