### ISSUE TITLE
Add logging when loading and unloading extensions

### ISSUE THREAD

**Issue by parafoxia** [tandemdude/hikari-lightbulb#148]
### Summary
A logging kwarg to output when an extension loads to the terminal.

### Problem
When loading extensions manually in a for loop, it's very easy to add your own logs. However, this is not the case with `load_extensions_from`.

### Ideal implementation
```py
BotApp.load_extensions_from(..., log=False)
```
or
```py
BotApp.load_extensions_from(..., output=False)
```

As `load_extension` does not log automatically, having this kwarg default to `False` would keep it consistent.

I plan to add this myself.

### Checklist
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment]
Making it optional is unnecessary - all the methods should log what they are doing instead.

**Comment by parafoxia** [comment]
Should I set the `load_extension` to log by default as well then? That would be within the scope of the issue still, pending a title change.

**Comment by tandemdude** [comment]
Load and unload should log ideally.

**Comment by parafoxia** [comment]
Okay cool, I'll add that in as well.

**Comment by parafoxia** [comment]
Okay it looks like I potentially missed something -- logging *does already* occur for loading and unloading, but happens at DEBUG level rather than INFO level. Slash command logging all happens at the INFO level, so should this be changed?
