### ISSUE TITLE
Allow an option to not have command options auto resolve

### ISSUE THREAD

**Issue by neonjonn** [tandemdude/hikari-lightbulb#175]
### Summary

Allow users to choose whether or not lightbulb auto resolves command options like `hikari.User`

### Why is this needed?

Allow users more control, if they want to fetch the options themselves maybe

### Ideal implementation

Probably adding an `auto_resolve=False` kwarg to command decorators, which defaults to `True`

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by parafoxia** [comment]
What format would the non-resolved options take? And would it only affect Hikari objects, or more generic ones like ints and bools too?

**Comment by neonjonn** [comment]
I'd probably have it return the ID of the object, it's the most useful. And it would only affect hikari objects like users and channels, to stop lightbulb fetching some information if you're gonna do it manually

**Comment by Jonxslays** [comment]
These options are resolved by hikari, not lightbulb. What you are actually looking for is `hikari.OptionType.MENTIONABLE`.

```py
@bot.command
@lightbulb.option("mentionable", "The mentionable to get", type=hikari.OptionType.MENTIONABLE)
@lightbulb.command("get", "Gets a user or channel id")
@lightbulb.implements(lightbulb.commands.SlashCommand)
async def echo(ctx: lightbulb.context.Context) -> None:
    m = ctx.options.mentionable

    print(type(m))
    print(m)
```
![image](https://user-images.githubusercontent.com/51417989/144716786-413cc68b-cd1a-4669-98f8-e4467c65d168.png)

![image](https://user-images.githubusercontent.com/51417989/144716790-8821c592-198f-4ab6-8168-f25b925a6be2.png)

**Comment by neonjonn** [comment]
Oh I see. Well in that case this issue is redundant I suppose.

**Comment by tandemdude** [comment]
> These options are resolved by hikari, not lightbulb. What you are actually looking for is `hikari.OptionType.MENTIONABLE`.
> 
> ```python
> @bot.command
> @lightbulb.option("mentionable", "The mentionable to get", type=hikari.OptionType.MENTIONABLE)
> @lightbulb.command("get", "Gets a user or channel id")
> @lightbulb.implements(lightbulb.commands.SlashCommand)
> async def echo(ctx: lightbulb.context.Context) -> None:
>     m = ctx.options.mentionable
> 
>     print(type(m))
>     print(m)
> ```
> 
> ![image](https://user-images.githubusercontent.com/51417989/144716786-413cc68b-cd1a-4669-98f8-e4467c65d168.png)
> 
> ![image](https://user-images.githubusercontent.com/51417989/144716790-8821c592-198f-4ab6-8168-f25b925a6be2.png)

Note that you can pass `hikari.Snowflake` in as the `type` instead of the OptionType directly

**Comment by neonjonn** [comment]
Forgot this issue was still open, I'll close it
