### ISSUE TITLE
Consider managing application commands atomically

### ISSUE THREAD

**Issue by norinorin** [tandemdude/hikari-lightbulb#187]
### Summary

This allows lightbulb-based apps to sync application commands with as few requests as possible.

### Why is this needed?

While it compares the local and the registered commands so that it won't make unnecessary requests, it's still gonna spam the API on first syncing (all commands are new and to be registered) or when there are many commands the metadata of which got changed. Using the PUT method instead would be nice for several reasons: no need to compare the commands and see if they change since it's bulk overwriting them; it's atomic, it may/may not be helpful if the bot goes down during the commands managing; fewer requests being made, getting rate limited could be avoided here.

### Ideal implementation

We can leave the non-atomic function at that and have an option for the atomic one, or just completely ditch it.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment]
Implemented in next release
