### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by parafoxia** [tandemdude/hikari-lightbulb#197]
### Steps to reproduce

https://github.com/tandemdude/hikari-lightbulb/blob/development/lightbulb/app.py#L275
https://github.com/tandemdude/hikari-lightbulb/blob/development/lightbulb/app.py#L968

### Expected result

```py
handle_message_create_for_prefix_commands
```

### Actual result

```py
handle_messsage_create_for_prefix_commands
```

### System info

```shell
Irrelevant
```

### Further info

Not gonna bother with a PR cos of how simple this is haha.

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment]
tHiS iS aCtUaLLy a fEAtuRe
