### ISSUE TITLE
Add max concurrency limit option

### ISSUE THREAD

**Issue by HyperGH** [tandemdude/hikari-lightbulb#216]
### Summary

This command decorator should allow for the command to only have x running instances per the specified bucket, and raise an error if this limit was exceeded.

### Why is this needed?

This feature would be extremely nice for commands that should not run more than one at a time (for example a typeracing command, where only a maximum of one instance of the command should be running in a channel at any given time), or commands that rely on their state not being altered by a different instance of themselves.

### Ideal implementation

Example syntax:

```py
@bot.command()
# A maximum of one instance per channel
@lightbulb.max_concurrency(1, lightbulb.ChannelBucket)
@lightbulb.command("thommo", "based")
@lightbulb.implements(...)
async def foo(ctx: lightbulb.Context) -> None:
    await asyncio.sleep(10.0) # Long operation
    await ctx.respond("foo")
```

Trying to execute a command that exceeded it's max concurrency should raise an error (for example: `lightbulb.MaxConcurrencyReachedError`) with information about the max uses & bucket-type used included in the exception.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by MakufonSkifto** [comment]
I feel like using this as a constructor in the command decorator would be better and easier to use
```py
@lightbulb.command("", "", max_concurrency=lightbulb.ChannelBucket(1))
```
