### ISSUE TITLE
pycharm does not recognize lightbulb module

### ISSUE THREAD

**Issue by 3BixxPy** [tandemdude/hikari-lightbulb#222]
### Steps to reproduce

1. i ran the pip install hikari-lightbulb
2. restarted pycharm
3. and tried to import lightbulb
4.

### Expected result

.

### Actual result

lightbulb not recognized

### System info

```shell
Traceback (most recent call last):
  File "C:\Users\xxxx\xxx\xxx\folders\discord_bot_py\bot.py", line 3, in <module>
    import lightbulb
ModuleNotFoundError: No module named 'lightbulb'
```

### Further info

havent tried it on visual studio code but i expect the same result

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by HyperGH** [comment]
This looks like an installation issue, not an issue with lightbulb. Please ensure you activated your venv, and that you installed lightbulb on the same version of the interpreter that you actually use.
