### ISSUE TITLE
Lightbulb Tasks

### ISSUE THREAD

**Issue by BlazingHellBlast** [tandemdude/hikari-lightbulb#254]
### Steps to reproduce

I've tried to run my bots code, however, i get the following error, due to importing tasks from lightbulb

### Expected result

It should have displayed the usual hikari text, instead it printed the traceback

### Actual result

```
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    from lightbulb.ext import tasks
ImportError: cannot import name 'tasks' from 'lightbulb.ext' (unknown location)

```

### System info

```shell
hikari-lightbulb (2.1.3)
hikari (2.0.0.dev108) [6dbab9a6]
located at /home/runner/Lynx-Main/venv/lib/python3.8/site-packages/hikari
CPython 3.8.12 GCC 10.3.0
Linux 355a27b5f37f 5.13.0-1027-gcp #32~20.04.1-Ubuntu SMP Thu May 26 10:53:08 UTC 2022 x86_64
~/Lynx-Main$
```

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
You are using an outdated version of lightbulb. Please update to the latest by using `pip install -U hikari-lightbulb`

Tasks where added on release 2.2.0 and you are using 2.1.3 (https://github.com/tandemdude/hikari-lightbulb/releases/tag/2.2.0)

**Comment by BlazingHellBlast** [comment]
> You are using an outdated version of lightbulb. Please update to the latest by using `pip install -U hikari-lightbulb`
> 
> Tasks where added on release 2.2.0 and you are using 2.1.3 (https://github.com/tandemdude/hikari-lightbulb/releases/tag/2.2.0)
Thank's alot, your a lifesaver yknow!
