### ISSUE TITLE
Access All Listeners within a Plugin

### ISSUE THREAD

**Issue by WildKadeGaming** [tandemdude/hikari-lightbulb#291]
### Summary

Being able to see all of the listeners within a plugin would be nice, so when wanting to get the function names or event types that the listeners subscribed to, you can do so for whatever reason necessary.

### Why is this needed?

Just like above, developers can access which event listeners are loaded into a plugin. and what their hooked functions are.

### Ideal implementation

```python
def load(client:lightbulb.BotApp) -> None:
    client.add_plugin(plugin)

    for event in plugin.all_listeners:
        ... # Do something with the event
```

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment]
Why specifically do you need the listeners registered to the specific plugin? You can already get all the listeners registered with the bot for a specific event by using `GatewayBot.get_listeners(event_type)`

**Comment by WildKadeGaming** [comment]
I would like to implement my own custom even subscribed log.

When I load all of a plugin's listeners, I would like to have all of the function names, etc. be available for developers to see so they can track when events are listened to and what functions are linked to them without hard-coding it.

**Comment by tandemdude** [comment]
subclass the bot and override the `subscribe` method which is used to register listeners

**Comment by WildKadeGaming** [comment]
Sounds good
