### ISSUE TITLE
Provide a add_hook as counter part of remove_hook

### ISSUE THREAD

**Issue by Shawn8901** [tandemdude/hikari-lightbulb#296]
### Summary

It would be very useful if a plugin could use some initialization code.
One could place it in the `Plugin.load()`-Method which is used to add the plugin, but that sadly does not support coroutines.
As for the remove part there is a `remove_hook` which also supports coroutines and is to be used for teardown it would be kinda consequent to have a tearup/setup method following the same logic.  

My usage scenario is at the moment that i am using hikari-lightbulb for a small bot that does print notification messages for events on a regular time (informing that something will happen soon in a game). Therefor i save those events in a database. When loading the plugin, which is responsible for those logic i have to load the events from the database somehow. I am using a async orm (tortoise orm in my case), which can not be used in the `Plugin.load()` method as it can not be a coroutine.

### Why is this needed?

When a plugin needs some initialization, e.G loading something from database, which does need the logic to be a coroutine this can not be implemented.

### Ideal implementation

Similar to the remove_hook.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment]
This is not possible as I cannot guarantee that an event loop exists when a plugin is added to the bot - i.e. before the bot has been started. If you want something similar you should have a plugin listener for either `hikari.StartingEvent` or `hikari.StartedEvent` to do your setup.

**Comment by Shawn8901** [comment]
Thanks for the explanation. 
I did not come around that, as i was building an eventloop anyways prior `Bot.start()` as i need some init before the bot at all.
But when using `Bot.run()` its creating the loop. So there you are completely right.
The suggested "workaround" works fine, thank you very much for that hint.

Closing the issue here, have a nice day and thank you for the project! :smiley:
