### ISSUE TITLE
Exception when message is deleted before navigator finished adding reactions

### ISSUE THREAD

**Issue by davfsa** [tandemdude/hikari-lightbulb#3]
when navigator runs, and it adds the stop button, if you click it before all the reactions have been added it will cause an error
 `hikari.errors.NotFoundError: Not Found 404: {"message": "Unknown Message", "code": 10008}` cause it tries to add them to a message that no longer exists

[*Original*](https://gitlab.com/tandemdude/lightbulb/-/issues/86)

**Comment by ahnaf-zamil** [comment]
So would it be good if you would check that the message still exists before adding the reactions?
For this method, it could check if the message exists, every time it is about add a reaction.

Or, we could implement this in another way. When you press the stop button, it would check if all the reactions are added to the message or not. If the reactions are all there, then it could safely delete the message as it won't throw an exception.

Let me know what you think.

**Comment by davfsa** [comment]
This can just be an easy fix by handling hikari errors. There is not need to check if the message is there after every reaction, at it is too many requests

**Comment by ahnaf-zamil** [comment]
https://github.com/tandemdude/hikari-lightbulb/blob/7f7131bf22f6a1e4abfacfe73799d47f7b737f1a/lightbulb/utils/nav.py#L231-L232

This line raises the `hikari.errors.NotFoundError` as the message was deleted. So just simply using a `try/except` for the error should fix it.
