### ISSUE TITLE
Rename permission check

### ISSUE THREAD

**Issue by YodaPY** [tandemdude/hikari-lightbulb#31]
### Summary
Rename the `bot_has_permissions` check to `bot_has_channel_permissions` for consistency with `bot_has_guild_permissions`

### Problem
Inconsistency and confusion

### Ideal implementation
Rename the functions

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by ahnaf-zamil** [comment]
Is this issue still valid?
