### ISSUE TITLE
Proxy support 

### ISSUE THREAD

**Issue by perlinson** [tandemdude/hikari-lightbulb#395]
### Summary

like this :
import discord
from discord.ext import commands
import os
import asyncio
intents = discord.Intents.default()
client = commands.Bot(command_prefix='~', intents=intents, proxy='http://127.0.0.1:7890')

### Why is this needed?

I need a proxy to access discord 

### Ideal implementation

To be decided.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by null-domain** [comment]
```py
import discord
from discord.ext import commands
import os
import asyncio
intents = discord.Intents.default()
client = commands.Bot(command_prefix='~', intents=intents, proxy='http://127.0.0.1:7890/')
```
This syntax looks like it belongs to [discord.py](https://github.com/Rapptz/discord.py), not Lightbulb. Did you mean to open an issue here?

**Comment by tandemdude** [comment]
If you are looking for a way to set proxy configuration with lightbulb's bot implementation, the parameter you need is `proxy_settings` inherited from [hikari.GatewayBot](https://docs.hikari-py.dev/en/latest/reference/hikari/impl/gateway_bot/#hikari.impl.gateway_bot.GatewayBot). Pass an instance of [ProxySettings](https://docs.hikari-py.dev/en/latest/reference/hikari/impl/config/#hikari.impl.config.ProxySettings) with the configuration you need.
