### ISSUE TITLE
Message objects in Message Commands lack some of the information, like guild_id and referenced_message

### ISSUE THREAD

**Issue by AjnoEO** [tandemdude/hikari-lightbulb#425]
### Steps to reproduce

1. Install the latest versions of hikari and hikari-lightbulb
2. Save this code:

```py
import hikari
import lightbulb

TOKEN = "your_token" # replace with your token

bot = lightbulb.BotApp(
    token=TOKEN,
    intents=hikari.Intents.ALL_UNPRIVILEGED | hikari.Intents.MESSAGE_CONTENT | hikari.Intents.GUILD_MEMBERS
)

@bot.command
@lightbulb.command(name="Test", description="Test")
@lightbulb.implements(lightbulb.MessageCommand)
async def test_command(ctx: lightbulb.MessageContext):
    message: hikari.Message = ctx.options.target
    await ctx.respond(
        f"""```\n"""
        f"""{message.content=}\n"""
        f"""{message.author=}\n"""
        f"""{message.type=}\n"""
        f"""{message.guild_id=}\n"""
        f"""{message.member=}\n"""
        f"""{message.referenced_message=}\n"""
        f"""```"""
        )
    
bot.run()
```

3. Run the code to start your bot. Invite it to a server.
4. Create a message, and then a reply to your message
5. Use the Test message command on the reply (The message menu > “Apps” > “Test”)
6. See the result

### Expected result

The message should display values of all the attributes correctly.

### Actual result

`message.guild_id`, `message.member` and `message.referenced_message` are `None`. The message type is `REPLY`, as intended, but the referenced message still has no value

### System info

```shell
hikari-lightbulb (2.3.5)
hikari (2.0.0.dev125) [8ff87e57]
located at C:\Users\boyko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\hikari
CPython 3.11.9 MSC v.1938 64 bit (AMD64)
Windows Ajno_tekkomp 10 10.0.22631 AMD64 AMD64 Family 23 Model 160 Stepping 0, AuthenticAMD
```

### Further info

![Example of the command being executed](https://github.com/tandemdude/hikari-lightbulb/assets/39632696/66122d2f-7891-4e4e-b239-815d1570707d)

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment]
This is not a lightbulb bug - this entirely depends on what data discord sends in the command interaction.
