### ISSUE TITLE
Does not resolve for hikari 2.1.0

### ISSUE THREAD

**Issue by piotr25691** [tandemdude/hikari-lightbulb#461]
### Steps to reproduce

1. Set your requirements.txt to require hikari==2.1.0 and hikari-lightbulb==2.3.5.post0
2. Run pip install -r requirements.txt
3. Experience ResolutionImpossible

### Expected result

Package should've installed correctly.

### Actual result

ERROR: Cannot install -r requirements.txt (line 4) and hikari==2.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested hikari==2.1.0
    hikari-lightbulb 2.3.5.post0 depends on hikari~=2.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### System info

```shell
Doesn't apply because of a dependency conflict.
```

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment]
This is not a bug. Hikari uses effver which means 2.1.0 represents a breaking change over 2.0.0. Lightbulb is compatible however so from next release 2.1.0 will be supported.
