### ISSUE TITLE
Greedy converters

### ISSUE THREAD

**Issue by parafoxia** [tandemdude/hikari-lightbulb#61]
### Summary
Currently converters can only take one of a particular object at one time. It would be good for there to be some sort of greedy converter functionality, similar to d.py, that could take multiple of a single object type and put it in a list.

### Problem
See above.

### Ideal implementation
```py
async def command(self, ctx, targets: lightbulb.greedy_member_converter):
    print(type(targets))

# Output:
<class 'list'> (or even tuple)
```
Or something like that. I'll leave you to decide how you think it would work best.

### Checklist
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by IkBenOlie5** [comment]
maybe `lightbulb.greedy(lightbulb.member_converter)` so it's not needed to create every converter twice. not sure if this is possible tho

**Comment by norinorin** [comment]
> maybe `lightbulb.greedy(lightbulb.member_converter)` so it's not needed to create every converter twice. not sure if this is possible tho

This sounds convenient, it's totally possible. But, I'm hoping this can be implemented as class types as mypy would complain about the invalid typehint.

**Comment by YodaPY** [comment]
As I already mentioned in the discord, I would just subclass `typing.Generic`, I don't think mypy will complain about that. 
Something like this looks clean and nice:
```py
async def command(ctx: Context, targets: lightbulb.Greedy[lightbulb.member_converter]) -> None: ...```

**Comment by norinorin** [comment]
> As I already mentioned in the discord, I would just subclass `typing.Generic`, I don't think mypy will complain about that.
> Something like this looks clean and nice:
> 
> ```python
> async def command(ctx: Context, targets: lightbulb.Greedy[lightbulb.member_converter]) -> None: ...
> ```

I did mean all the built-in converters. Such as lightbulb.member_converter which is a function.
