### ISSUE TITLE
Change dynamic cooldown callbacks return type to optional

### ISSUE THREAD

**Issue by Tmpod** [tandemdude/hikari-lightbulb#67]
### Summary

The return type of dynamic cooldown callbacks should be an `Optional`. This would essentially disable the cooldown for the given condition.

### Problem

At the moment, it's still unpractical to lift any invocation rate restrictions on specific people, roles, or any predicate in general. The `dynamic_cooldown` utility was a nice addition, but one still has to write a custom manager in order to achieve that behaviour.

### Ideal implementation

Some type signatures would have to change and the implementation of `add_cooldown` would have to return early if the result of `_get_bucket` is `None`.

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by Tmpod** [comment]
I will making a quick PR to fix this @tandemdude

**Comment by tandemdude** [comment]
Why can't you just return a bucket of zero length?

**Comment by Tmpod** [comment]
That sounds more like a cheap hack rather than a feature.

**Comment by tandemdude** [comment]
It just seems like a completely unnecessary change to me. A bucket of zero length is far more explicit in my opinion.

**Comment by Tmpod** [comment]
I politely disagree. I believe adding the `Optional` to the type signature convey much more explicitly that there is a way to bypass any cooldown without hacks, and that it is the intended way. I'd like someone else's opinion on this too :) 

Ultimately, the lib is yours ofc, so it's your call. Close the PR and issue if you don't want it.

**Comment by Tmpod** [comment]
Additionally, as I just realized when replying to a comment on the hikari Discord channel, issuing an empty bucket won't achieve the same behaviour as what I implemented. 

Quoting my message on Discord:
> Let's consider this case: a user runs the command with a dynamic cooldown that, for that specific context issues a UserBucket. However, before that cooldown expires, something changes and the user should not get stopped the next time they run the command. If you make the dynamic callback issue an empty bucket in those conditions, it won't actually prevent the cooldown because there's already an active UserBucket with that user's ID has the hash. Allowing the callback to return None not only explicitly declares that there's a clear option not to apply any form of cooldown in the type signature itself, but it **does** actually achieve such an effect.

thommo ended up suggesting an enum instead of just `None` due to the ambiguity it can bring. Does it simply not add any buckets, or does it reset existing ones? An enum will make this very clear.

**Comment by tandemdude** [comment]
Closing because stale
