### ISSUE TITLE
Add more properties to errors

### ISSUE THREAD

**Issue by IkBenOlie5** [tandemdude/hikari-lightbulb#68]
### Summary
Add more properties to errors to make it easier to create custom error messages. e.g.  lightbulb.errors.NSFWChannelOnly would have a command property and a channel property etc

### Problem
Make it easier to create custom error messages

### Ideal implementation
just CommandErrorEvent.exception.command etc

### Checklist
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment]
This seems unnecessary to me as the [CommandErrorEvent](https://hikari-lightbulb.readthedocs.io/en/latest/api-reference.html#lightbulb.events.CommandErrorEvent) already contains all this information and more. The only time you *may* see errors without being wrapped by a CommandErrorEvent would be if you are catching them manually __inside__ a command or listener in which case you again, already have access to all this information.

**Comment by IkBenOlie5** [comment]
ah ofc, i forgot u can get most of the info from context
