### ISSUE TITLE
Black- and whitelist check to make black- and whitelists command independent

### ISSUE THREAD

**Issue by IkBenOlie5** [tandemdude/hikari-lightbulb#78]
### Summary
A black- and whitelist check where you would be able to put a list of userids into and those people wouldn't or would be able to use the command.

### Problem
This makes black- and whitelists command independent and you won't have to check in the command itself.

### Ideal implementation
@checks.blacklist(user_ids=[...], role_ids=[...], guild_ids=[...], channel_ids=[...])

@checks.whitelist(user_ids=[...], role_ids=[...], guild_ids=[...], channel_ids=[...])

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
- [x] If it is a follow up of another issue, I have specified it.

**Comment by YodaPY** [comment]
The implementation might get a bit messy if you are going to add support for Guild, Channel and Role IDs

**Comment by IkBenOlie5** [comment]
Why? Can't you just add extra arguments? (didn't think of guild and role ids before but seems like a good idea)

**Comment by tandemdude** [comment]
I don't think the implementation would get too messy.

**Comment by ben2224** [comment]
ability to pass a callable that returns a sequence of ids here would be more useful - although at that point its almost just a custom check, but I don't see much use for it other than for initial development but you can just use owner_only()

**Comment by IkBenOlie5** [comment]
> ability to pass a callable that returns a sequence of ids here would be more useful - although at that point its almost just a custom check, but I don't see much use for it other than for initial development but you can just use owner_only()

premium bots

**Comment by ben2224** [comment]
> premium bots

even so, most bots aren't premium and a callable would be more useful

**Comment by IkBenOlie5** [comment]
I think being able to pass a callable could be useful

**Comment by tandemdude** [comment]
may as well just use a custom check at that point
